apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: go-x
  labels:
    app: gateway
spec:
  ports:
    - port: 30200
      name: ""
  clusterIP: None
  selector:
    app: gateway

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gateway
  namespace: go-x
  labels:
    app: gateway
spec:
  serviceName: gateway
  selector:
    matchLabels:
      app: gateway
  replicas: 2
  template:
    metadata:
      labels:
        app: gateway
    spec:
      serviceAccountName: sa-go-x
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: gateway
        image: 127.0.0.1:5000/fananchong/go-x
        imagePullPolicy: Always
        command: [ "./gateway" ]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace


