[common]
Version = "0.0.1"
LogDir = "./logs"
LogLevel = 0
Debug = true
IntranetToken = "6d8f1f3a-739f-47fe-9ed1-ea39276cd10d"

[dbaccount]
Name = "account"
Addrs = ["redis.go-x:6379"]
Password = ""
DBIndex = 0

[dbtoken]
Name = "token"
Addrs = ["redis.go-x:6379"]
Password = ""
DBIndex = 0

[dbserver]
Name = "server"
Addrs = ["redis.go-x:6379"]
Password = ""
DBIndex = 0

[login]
Listen = ":8080"
Sign1 = "5UY6$f$h"
Sign2 = "3wokZB%q"
Sign3 = "%2Fi9TRf"

[gateway]
Connect = [3, 5]            #1: login; 2: gateway; 3: lobby; 4: room; 5: hub


[lobby]

[hub]

